DROP DATABASE escola;
CREATE DATABASE escola;
USE escola;

CREATE TABLE alunos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(127) NOT NULL,
    idade INT NOT NULL,
    matricula VARCHAR(20) NOT NULL
);

CREATE TABLE Professores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(127) NOT NULL,
    cpf CHAR(14) NOT NULL,
    especializacao VARCHAR(127) NOT NULL
);  